name: Compile the document

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
            lfs: true
  
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
            remote: true
    
      - name: Compile the listings-example document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs/listings
          root_file: lstexample.tex
  
      - name: Compile the first example
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs/example1
          root_file: example1.tex

      - name: Compile the uebungsblatt
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs/uebungsblatt
          root_file: uebungsblatt.tex

      - name: Compile the main document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: latexbasics.tex

      - name: Commit PDF
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f latexbasics.pdf
          git commit -m "Update PDF by workflow"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: "gh-pages"
          github_token: ${{ secrets.GITHUB_TOKEN }}

